---
fixtures:
  repositories:
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
