fixtures:
  repositories:
    chocolatey: "https://github.com/puppetlabs/puppetlabs-chocolatey"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    firefox: "#{source_dir}"
